// Code generated by aliasgen. DO NOT EDIT.
// To regenerate, run: go generate ./server/fleet/...
//
// This file contains MarshalJSON implementations that output both deprecated
// and new API field names for backwards compatibility. The mapping is defined
// in api_aliases.go.
package fleet

import "encoding/json"

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ABMTokenTeam) MarshalJSON() ([]byte, error) {
	type Original ABMTokenTeam
	return json.Marshal(&struct {
		Original
		ID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:      Original(o),
		ID_NewAPIName: o.ID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityAddedAppStoreApp) MarshalJSON() ([]byte, error) {
	type Original ActivityAddedAppStoreApp
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityDeletedAppStoreApp) MarshalJSON() ([]byte, error) {
	type Original ActivityDeletedAppStoreApp
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityEditedAppStoreApp) MarshalJSON() ([]byte, error) {
	type Original ActivityEditedAppStoreApp
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityEditedSetupExperienceSoftware) MarshalJSON() ([]byte, error) {
	type Original ActivityEditedSetupExperienceSoftware
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeAddedBootstrapPackage) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeAddedBootstrapPackage
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeAddedCertificate) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeAddedCertificate
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeAddedScript) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeAddedScript
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeAddedSoftware) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeAddedSoftware
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeBatchScriptScheduled) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeBatchScriptScheduled
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeChangedMacosSetupAssistant) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeChangedMacosSetupAssistant
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeChangedUserTeamRole) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeChangedUserTeamRole
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeCreatedAndroidProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeCreatedAndroidProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeCreatedDeclarationProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeCreatedDeclarationProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeCreatedMacosProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeCreatedMacosProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeCreatedPolicy) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeCreatedPolicy
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *int64 `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeCreatedSavedQuery) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeCreatedSavedQuery
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName int64 `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeCreatedTeam) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeCreatedTeam
	return json.Marshal(&struct {
		Original
		ID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:      Original(o),
		ID_NewAPIName: o.ID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeCreatedWindowsProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeCreatedWindowsProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedAndroidProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedAndroidProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedBootstrapPackage) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedBootstrapPackage
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedCertificate) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedCertificate
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedDeclarationProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedDeclarationProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedMacosProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedMacosProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedMacosSetupAssistant) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedMacosSetupAssistant
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedMultipleSavedQuery) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedMultipleSavedQuery
	return json.Marshal(&struct {
		Original
		Teamid_NewAPIName int64 `json:"fleet_id"`
	}{
		Original:          Original(o),
		Teamid_NewAPIName: o.Teamid,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedPolicy) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedPolicy
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *int64 `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedSavedQuery) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedSavedQuery
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName int64 `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedScript) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedScript
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedSoftware) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedSoftware
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedTeam) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedTeam
	return json.Marshal(&struct {
		Original
		ID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:      Original(o),
		ID_NewAPIName: o.ID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedUserTeamRole) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedUserTeamRole
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDeletedWindowsProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDeletedWindowsProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDisabledConditionalAccessAutomations) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDisabledConditionalAccessAutomations
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDisabledMacosDiskEncryption) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDisabledMacosDiskEncryption
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDisabledMacosSetupEndUserAuth) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDisabledMacosSetupEndUserAuth
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeDisabledMacosUpdateNewHosts) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeDisabledMacosUpdateNewHosts
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedAgentOptions) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedAgentOptions
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedAndroidCertificate) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedAndroidCertificate
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedAndroidProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedAndroidProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedDeclarationProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedDeclarationProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedIOSMinVersion) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedIOSMinVersion
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedIPadOSMinVersion) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedIPadOSMinVersion
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedMacOSMinVersion) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedMacOSMinVersion
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedMacosProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedMacosProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedPolicy) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedPolicy
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *int64 `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedSavedQuery) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedSavedQuery
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName int64 `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedScript) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedScript
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedSoftware) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedSoftware
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedWindowsProfile) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedWindowsProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEditedWindowsUpdates) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEditedWindowsUpdates
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEnabledConditionalAccessAutomations) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEnabledConditionalAccessAutomations
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEnabledMacosDiskEncryption) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEnabledMacosDiskEncryption
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEnabledMacosSetupEndUserAuth) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEnabledMacosSetupEndUserAuth
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeEnabledMacosUpdateNewHosts) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeEnabledMacosUpdateNewHosts
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeRanScriptBatch) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeRanScriptBatch
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeTransferredHostsToTeam) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeTransferredHostsToTeam
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ActivityTypeUpdatedScript) MarshalJSON() ([]byte, error) {
	type Original ActivityTypeUpdatedScript
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o AuthzSoftwareInventory) MarshalJSON() ([]byte, error) {
	type Original AuthzSoftwareInventory
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o BatchActivity) MarshalJSON() ([]byte, error) {
	type Original BatchActivity
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o BatchExecutionStatusFilter) MarshalJSON() ([]byte, error) {
	type Original BatchExecutionStatusFilter
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o EnrollSecret) MarshalJSON() ([]byte, error) {
	type Original EnrollSecret
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o Host) MarshalJSON() ([]byte, error) {
	type Original Host
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o HostHealth) MarshalJSON() ([]byte, error) {
	type Original HostHealth
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o HostMDMCheckinInfo) MarshalJSON() ([]byte, error) {
	type Original HostMDMCheckinInfo
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o HostScriptRequestPayload) MarshalJSON() ([]byte, error) {
	type Original HostScriptRequestPayload
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o HostScriptResult) MarshalJSON() ([]byte, error) {
	type Original HostScriptResult
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o HostSummary) MarshalJSON() ([]byte, error) {
	type Original HostSummary
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o Label) MarshalJSON() ([]byte, error) {
	type Original Label
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o LabelSpec) MarshalJSON() ([]byte, error) {
	type Original LabelSpec
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o LabelSummary) MarshalJSON() ([]byte, error) {
	type Original LabelSummary
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMAndroidConfigProfile) MarshalJSON() ([]byte, error) {
	type Original MDMAndroidConfigProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMAppleBootstrapPackage) MarshalJSON() ([]byte, error) {
	type Original MDMAppleBootstrapPackage
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMAppleConfigProfile) MarshalJSON() ([]byte, error) {
	type Original MDMAppleConfigProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMAppleDeclaration) MarshalJSON() ([]byte, error) {
	type Original MDMAppleDeclaration
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMAppleSettingsPayload) MarshalJSON() ([]byte, error) {
	type Original MDMAppleSettingsPayload
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMAppleSetupAssistant) MarshalJSON() ([]byte, error) {
	type Original MDMAppleSetupAssistant
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMAppleSetupPayload) MarshalJSON() ([]byte, error) {
	type Original MDMAppleSetupPayload
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMCommandAuthz) MarshalJSON() ([]byte, error) {
	type Original MDMCommandAuthz
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMConfigProfileAuthz) MarshalJSON() ([]byte, error) {
	type Original MDMConfigProfileAuthz
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMConfigProfilePayload) MarshalJSON() ([]byte, error) {
	type Original MDMConfigProfilePayload
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o MDMWindowsConfigProfile) MarshalJSON() ([]byte, error) {
	type Original MDMWindowsConfigProfile
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o Pack) MarshalJSON() ([]byte, error) {
	type Original Pack
	return json.Marshal(&struct {
		Original
		TeamIDs_NewAPIName []uint `json:"fleet_ids"`
	}{
		Original:           Original(o),
		TeamIDs_NewAPIName: o.TeamIDs,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o PackPayload) MarshalJSON() ([]byte, error) {
	type Original PackPayload
	return json.Marshal(&struct {
		Original
		TeamIDs_NewAPIName *[]uint `json:"fleet_ids"`
	}{
		Original:           Original(o),
		TeamIDs_NewAPIName: o.TeamIDs,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o PolicyData) MarshalJSON() ([]byte, error) {
	type Original PolicyData
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o Query) MarshalJSON() ([]byte, error) {
	type Original Query
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o QueryPayload) MarshalJSON() ([]byte, error) {
	type Original QueryPayload
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o QueryStats) MarshalJSON() ([]byte, error) {
	type Original QueryStats
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o Script) MarshalJSON() ([]byte, error) {
	type Original Script
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o ScriptResponse) MarshalJSON() ([]byte, error) {
	type Original ScriptResponse
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o SoftwareAutoUpdateSchedule) MarshalJSON() ([]byte, error) {
	type Original SoftwareAutoUpdateSchedule
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o SoftwareInstaller) MarshalJSON() ([]byte, error) {
	type Original SoftwareInstaller
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o SoftwareInstallerTokenMetadata) MarshalJSON() ([]byte, error) {
	type Original SoftwareInstallerTokenMetadata
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o SoftwarePackageResponse) MarshalJSON() ([]byte, error) {
	type Original SoftwarePackageResponse
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o SoftwareTitleIcon) MarshalJSON() ([]byte, error) {
	type Original SoftwareTitleIcon
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o TeamTuple) MarshalJSON() ([]byte, error) {
	type Original TeamTuple
	return json.Marshal(&struct {
		Original
		ID_NewAPIName uint `json:"fleet_id"`
	}{
		Original:      Original(o),
		ID_NewAPIName: o.ID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o VPPApp) MarshalJSON() ([]byte, error) {
	type Original VPPApp
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id,omitempty"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}

// MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
func (o VPPAppResponse) MarshalJSON() ([]byte, error) {
	type Original VPPAppResponse
	return json.Marshal(&struct {
		Original
		TeamID_NewAPIName *uint `json:"fleet_id"`
	}{
		Original:          Original(o),
		TeamID_NewAPIName: o.TeamID,
	})
}
