// Command aliasgen scans Go files for structs with JSON fields that match
// deprecated API field names and generates MarshalJSON implementations that
// include both the deprecated and new field names in JSON output.
//
// This is used to support API field renaming (e.g., team_id -> fleet_id) while
// maintaining backwards compatibility by outputting both field names.
//
// The mapping of deprecated -> new field names is read from a Go source file
// containing a map[string]string variable.
//
// Usage:
//
//	go run ./server/fleet/aliasgen -pkg ./server/fleet -o ./server/fleet/json_aliases.go
//
// Or via go:generate in server/fleet/fleet.go:
//
//	//go:generate go run ./aliasgen -pkg . -o json_aliases.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/imports"
)

// AliasMapVarName is the name of the variable in the source package that
// contains the mapping of deprecated field names to new field names.
const AliasMapVarName = "APIFieldAliases"

// AliasMapFileName is the file expected to contain the alias mapping.
const AliasMapFileName = "api_aliases.go"

const generatedHeader = `// Code generated by aliasgen. DO NOT EDIT.
  // To regenerate, run: go generate ./server/fleet/...
  //
  // This file contains MarshalJSON implementations that output both deprecated
  // and new API field names for backwards compatibility. The mapping is defined
  // in %s.

  package %s

  import "encoding/json"
  `

// AliasedField represents a struct field that needs aliasing in JSON output.
type AliasedField struct {
	Name           string // Go field name, e.g., "TeamID"
	DeprecatedName string // deprecated json name, e.g., "team_id"
	NewName        string // new json name, e.g., "fleet_id"
	Type           string // field type, e.g., "*uint"
	Omitempty      bool
}

// AliasedStruct represents a struct that has at least one field needing aliasing.
type AliasedStruct struct {
	Name   string
	Fields []AliasedField
}

func main() {
	pkgPath := flag.String("pkg", ".", "package directory to scan")
	outFile := flag.String("o", "", "output file (stdout if empty)")
	flag.Parse()

	fset := token.NewFileSet()

	// Parse the alias mapping from the source package
	aliases, err := parseAliasMapping(fset, *pkgPath)
	if err != nil {
		log.Fatalf("Error parsing alias mapping: %v", err)
	}

	if len(aliases) == 0 {
		log.Printf("No aliases defined in %s (or %s not found)", AliasMapVarName, AliasMapFileName)
		return
	}

	log.Printf("Found %d field aliases in %s", len(aliases), AliasMapVarName)
	for deprecated, newName := range aliases {
		log.Printf("  %s -> %s", deprecated, newName)
	}

	// Find structs with fields that match deprecated names
	structs, pkgName, err := findStructsNeedingAliases(fset, *pkgPath, aliases)
	if err != nil {
		log.Fatalf("Error scanning package: %v", err)
	}

	// Find existing MarshalJSON implementations to skip
	existing, err := findExistingMarshalers(fset, *pkgPath)
	if err != nil {
		log.Fatalf("Error finding existing marshalers: %v", err)
	}

	// Filter out structs that already have MarshalJSON and warn
	var toGenerate []AliasedStruct
	for _, s := range structs {
		if existing[s.Name] {
			log.Printf("WARNING: %s has deprecated fields but already implements MarshalJSON - skipping (needs manual update)", s.Name)
			continue
		}
		toGenerate = append(toGenerate, s)
	}

	if len(toGenerate) == 0 {
		log.Printf("No structs need MarshalJSON generation")
		// Remove existing generated file if it exists and we have nothing to generate
		if *outFile != "" {
			if _, err := os.Stat(*outFile); err == nil {
				log.Printf("Removing %s (no aliases to generate)", *outFile)
				os.Remove(*outFile)
			}
		}
		return
	}

	// Sort by struct name for deterministic output
	sort.Slice(toGenerate, func(i, j int) bool {
		return toGenerate[i].Name < toGenerate[j].Name
	})

	src, err := generateMarshalers(pkgName, toGenerate)
	if err != nil {
		log.Fatalf("Error generating code: %v", err)
	}

	if *outFile == "" {
		fmt.Println(string(src))
	} else {
		if err := os.WriteFile(*outFile, src, 0o644); err != nil {
			log.Fatalf("Error writing output file: %v", err)
		}
		log.Printf("Generated %s with %d MarshalJSON implementations:", *outFile, len(toGenerate))
		for _, s := range toGenerate {
			var fieldNames []string
			for _, f := range s.Fields {
				fieldNames = append(fieldNames, fmt.Sprintf("%s->%s", f.DeprecatedName, f.NewName))
			}
			log.Printf("  %s: %s", s.Name, strings.Join(fieldNames, ", "))
		}
	}
}

// parseAliasMapping reads the APIFieldAliases map from the package's api_aliases.go file.
func parseAliasMapping(fset *token.FileSet, pkgPath string) (map[string]string, error) {
	filename := pkgPath + "/" + AliasMapFileName
	file, err := parser.ParseFile(fset, filename, nil, 0)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("parsing %s: %w", filename, err)
	}

	aliases := make(map[string]string)

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.VAR {
			continue
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			for i, name := range valueSpec.Names {
				if name.Name != AliasMapVarName {
					continue
				}

				if i >= len(valueSpec.Values) {
					continue
				}

				// Parse the composite literal (map[string]string{...})
				compLit, ok := valueSpec.Values[i].(*ast.CompositeLit)
				if !ok {
					continue
				}

				for _, elt := range compLit.Elts {
					kv, ok := elt.(*ast.KeyValueExpr)
					if !ok {
						continue
					}

					// Extract key and value strings
					keyLit, ok := kv.Key.(*ast.BasicLit)
					if !ok || keyLit.Kind != token.STRING {
						continue
					}
					valLit, ok := kv.Value.(*ast.BasicLit)
					if !ok || valLit.Kind != token.STRING {
						continue
					}

					// Remove quotes from string literals
					key := strings.Trim(keyLit.Value, `"`)
					val := strings.Trim(valLit.Value, `"`)
					aliases[key] = val
				}
			}
		}
	}

	return aliases, nil
}

// findStructsNeedingAliases scans the package for structs with JSON fields
// that match deprecated field names in the alias mapping.
func findStructsNeedingAliases(fset *token.FileSet, pkgPath string, aliases map[string]string) ([]AliasedStruct, string, error) {
	pkgs, err := parser.ParseDir(fset, pkgPath, sourceFileFilter, 0)
	if err != nil {
		return nil, "", fmt.Errorf("parsing package: %w", err)
	}

	var structs []AliasedStruct
	var pkgName string

	for name, pkg := range pkgs {
		pkgName = name
		for _, file := range pkg.Files {
			fileStructs := findStructsInFile(fset, file, aliases)
			structs = append(structs, fileStructs...)
		}
	}

	return structs, pkgName, nil
}

// sourceFileFilter filters out test files and the generated aliases file.
func sourceFileFilter(fi os.FileInfo) bool {
	name := fi.Name()
	return !strings.HasSuffix(name, "_test.go") &&
		!strings.HasSuffix(name, "_aliases.go") &&
		!strings.HasPrefix(name, ".")
}

// findStructsInFile finds all structs with aliased fields in a single file.
func findStructsInFile(fset *token.FileSet, file *ast.File, aliases map[string]string) []AliasedStruct {
	var structs []AliasedStruct

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			aliasedFields := findAliasedFieldsInStruct(fset, structType, aliases)
			if len(aliasedFields) > 0 {
				structs = append(structs, AliasedStruct{
					Name:   typeSpec.Name.Name,
					Fields: aliasedFields,
				})
			}
		}
	}

	return structs
}

// findAliasedFieldsInStruct finds all fields with JSON names that match deprecated names.
func findAliasedFieldsInStruct(fset *token.FileSet, st *ast.StructType, aliases map[string]string) []AliasedField {
	var fields []AliasedField

	for _, field := range st.Fields.List {
		if field.Tag == nil {
			continue
		}

		// Parse the json tag
		tagValue := strings.Trim(field.Tag.Value, "`")
		jsonTag := extractTagValue(tagValue, "json")
		if jsonTag == "" || jsonTag == "-" {
			continue
		}

		jsonName, omitempty := parseJSONTag(jsonTag)

		// Check if this JSON field name is in our deprecated aliases
		newName, isDeprecated := aliases[jsonName]
		if !isDeprecated {
			continue
		}

		// Get field name (skip anonymous/embedded fields)
		if len(field.Names) == 0 {
			log.Printf("WARNING: embedded field with json:\"%s\" found, skipping (not supported)", jsonName)
			continue
		}
		fieldName := field.Names[0].Name

		// Get field type as string
		var typeBuf bytes.Buffer
		if err := format.Node(&typeBuf, fset, field.Type); err != nil {
			log.Printf("WARNING: could not format type for field %s: %v", fieldName, err)
			continue
		}

		fields = append(fields, AliasedField{
			Name:           fieldName,
			DeprecatedName: jsonName,
			NewName:        newName,
			Type:           typeBuf.String(),
			Omitempty:      omitempty,
		})
	}

	return fields
}

// extractTagValue extracts a specific tag value from a struct tag string.
func extractTagValue(tag, key string) string {
	// Simple parser for struct tags
	for tag != "" {
		// Skip leading whitespace
		i := 0
		for i < len(tag) && tag[i] == ' ' {
			i++
		}
		tag = tag[i:]
		if tag == "" {
			break
		}

		// Find the key
		i = 0
		for i < len(tag) && tag[i] != ':' && tag[i] != ' ' {
			i++
		}
		if i >= len(tag) {
			break
		}
		tagKey := tag[:i]
		tag = tag[i:]

		if tag == "" || tag[0] != ':' {
			continue
		}
		tag = tag[1:]

		if tag == "" || tag[0] != '"' {
			continue
		}
		tag = tag[1:]

		// Find the closing quote
		i = 0
		for i < len(tag) && tag[i] != '"' {
			if tag[i] == '\\' && i+1 < len(tag) {
				i++
			}
			i++
		}
		if i >= len(tag) {
			break
		}

		value := tag[:i]
		tag = tag[i+1:]

		if tagKey == key {
			return value
		}
	}
	return ""
}

// parseJSONTag parses a json struct tag into its name and omitempty flag.
func parseJSONTag(tag string) (name string, omitempty bool) {
	parts := strings.Split(tag, ",")
	name = parts[0]
	for _, p := range parts[1:] {
		if p == "omitempty" {
			omitempty = true
		}
	}
	return
}

// findExistingMarshalers finds all types in the package that already have MarshalJSON methods.
func findExistingMarshalers(fset *token.FileSet, pkgPath string) (map[string]bool, error) {
	pkgs, err := parser.ParseDir(fset, pkgPath, sourceFileFilter, 0)
	if err != nil {
		return nil, fmt.Errorf("parsing package: %w", err)
	}

	existing := make(map[string]bool)

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				funcDecl, ok := decl.(*ast.FuncDecl)
				if !ok {
					continue
				}

				// Check if it's a MarshalJSON method
				if funcDecl.Name.Name != "MarshalJSON" {
					continue
				}

				// Check if it has a receiver
				if funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
					continue
				}

				// Extract receiver type name
				recvType := funcDecl.Recv.List[0].Type
				typeName := extractTypeName(recvType)
				if typeName != "" {
					existing[typeName] = true
				}
			}
		}
	}

	return existing, nil
}

// extractTypeName extracts the type name from a receiver expression.
// Handles both value receivers (T) and pointer receivers (*T).
func extractTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			return ident.Name
		}
	}
	return ""
}

// generateMarshalers generates the MarshalJSON implementations for all aliased structs.
func generateMarshalers(pkgName string, structs []AliasedStruct) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, generatedHeader, AliasMapFileName, pkgName)

	for _, s := range structs {
		if err := generateMarshaler(&buf, s); err != nil {
			return nil, fmt.Errorf("generating marshaler for %s: %w", s.Name, err)
		}
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w", err)
	}

	// Fix imports
	result, err := imports.Process("", formatted, nil)
	if err != nil {
		return nil, fmt.Errorf("processing imports: %w", err)
	}

	return result, nil
}

// generateMarshaler generates a MarshalJSON implementation for a single struct.
func generateMarshaler(buf *bytes.Buffer, s AliasedStruct) error {
	// Build the alias field declarations
	var aliasFieldDecls []string
	var aliasFieldAssignments []string

	for _, f := range s.Fields {
		// Build json tag for the new field name
		jsonTag := f.NewName
		if f.Omitempty {
			jsonTag += ",omitempty"
		}

		// Use a descriptive name for the alias field
		aliasFieldName := f.Name + "_NewAPIName"

		aliasFieldDecls = append(aliasFieldDecls,
			fmt.Sprintf("\t\t%s %s `json:\"%s\"`", aliasFieldName, f.Type, jsonTag))

		aliasFieldAssignments = append(aliasFieldAssignments,
			fmt.Sprintf("\t\t%s: o.%s,", aliasFieldName, f.Name))
	}

	// Write the method
	fmt.Fprintf(buf, `
  // MarshalJSON implements json.Marshaler to add aliased API fields for backwards compatibility.
  func (o %s) MarshalJSON() ([]byte, error) {
        type Original %s
        return json.Marshal(&struct {
                Original
  %s
        }{
                Original: Original(o),
  %s
        })
  }
  `, s.Name, s.Name, strings.Join(aliasFieldDecls, "\n"), strings.Join(aliasFieldAssignments, "\n"))

	return nil
}
