// Command aliasgen scans Go files for structs with API alias tags and generates
// MarshalJSON implementations that include aliased fields in JSON output.
//
// This is used to support API field renaming (e.g., team_id -> fleet_id) while
// maintaining backwards compatibility by outputting both field names.
//
// Usage:
//
//	go run ./server/fleet/aliasgen -pkg ./server/fleet -o ./server/fleet/json_aliases.go
//
// Or via go:generate in server/fleet/fleet.go:
//
//	//go:generate go run ./aliasgen -pkg . -o json_aliases.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"reflect"
	"strings"

	"golang.org/x/tools/imports"
)

// AliasTagName is the struct tag used to specify an API alias for a field.
// For example: `json:"team_id" api_alias:"fleet_id"`
const AliasTagName = "api_alias"

const generatedHeader = `// Code generated by aliasgen. DO NOT EDIT.
  // To regenerate, run: go generate ./server/fleet/...

  package %s

  import "encoding/json"
  `

// AliasedField represents a struct field with an alias tag.
type AliasedField struct {
	Name      string // Go field name, e.g., "TeamID"
	JSONName  string // json tag name, e.g., "team_id"
	AliasName string // alias tag name, e.g., "fleet_id"
	Type      string // field type, e.g., "*uint"
	Omitempty bool
}

// AliasedStruct represents a struct that has at least one aliased field.
type AliasedStruct struct {
	Name   string
	Fields []AliasedField
}

func main() {
	pkgPath := flag.String("pkg", ".", "package directory to scan")
	outFile := flag.String("o", "", "output file (stdout if empty)")
	flag.Parse()

	fset := token.NewFileSet()

	structs, pkgName, err := findAliasedStructs(fset, *pkgPath)
	if err != nil {
		log.Fatalf("Error scanning package: %v", err)
	}

	existing, err := findExistingMarshalers(fset, *pkgPath)
	if err != nil {
		log.Fatalf("Error finding existing marshalers: %v", err)
	}

	// Filter out structs that already have MarshalJSON and warn
	var toGenerate []AliasedStruct
	for _, s := range structs {
		if existing[s.Name] {
			log.Printf("WARNING: %s has %s tags but already implements MarshalJSON - skipping (needs manual update)", s.Name, AliasTagName)
			continue
		}
		toGenerate = append(toGenerate, s)
	}

	if len(toGenerate) == 0 {
		log.Printf("No structs with %s tags found (or all already have MarshalJSON)", AliasTagName)
		// Remove existing generated file if it exists and we have nothing to generate
		if *outFile != "" {
			if _, err := os.Stat(*outFile); err == nil {
				log.Printf("Removing %s (no aliases to generate)", *outFile)
				os.Remove(*outFile)
			}
		}
		return
	}

	src, err := generateMarshalers(pkgName, toGenerate)
	if err != nil {
		log.Fatalf("Error generating code: %v", err)
	}

	if *outFile == "" {
		fmt.Println(string(src))
	} else {
		if err := os.WriteFile(*outFile, src, 0o644); err != nil {
			log.Fatalf("Error writing output file: %v", err)
		}
		log.Printf("Generated %s with %d MarshalJSON implementations", *outFile, len(toGenerate))
		for _, s := range toGenerate {
			var fieldNames []string
			for _, f := range s.Fields {
				fieldNames = append(fieldNames, fmt.Sprintf("%s->%s", f.JSONName, f.AliasName))
			}
			log.Printf("  %s: %s", s.Name, strings.Join(fieldNames, ", "))
		}
	}
}

// findAliasedStructs scans the package for structs with alias tags on their fields.
func findAliasedStructs(fset *token.FileSet, pkgPath string) ([]AliasedStruct, string, error) {
	pkgs, err := parser.ParseDir(fset, pkgPath, sourceFileFilter, 0)
	if err != nil {
		return nil, "", fmt.Errorf("parsing package: %w", err)
	}

	var structs []AliasedStruct
	var pkgName string

	for name, pkg := range pkgs {
		pkgName = name
		for _, file := range pkg.Files {
			fileStructs := findAliasedStructsInFile(fset, file)
			structs = append(structs, fileStructs...)
		}
	}

	return structs, pkgName, nil
}

// sourceFileFilter filters out test files and the generated aliases file.
func sourceFileFilter(fi os.FileInfo) bool {
	name := fi.Name()
	return !strings.HasSuffix(name, "_test.go") &&
		!strings.HasSuffix(name, "_aliases.go") &&
		!strings.HasPrefix(name, ".")
}

// findAliasedStructsInFile finds all structs with aliased fields in a single file.
func findAliasedStructsInFile(fset *token.FileSet, file *ast.File) []AliasedStruct {
	var structs []AliasedStruct

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			aliasedFields := findAliasedFieldsInStruct(fset, structType)
			if len(aliasedFields) > 0 {
				structs = append(structs, AliasedStruct{
					Name:   typeSpec.Name.Name,
					Fields: aliasedFields,
				})
			}
		}
	}

	return structs
}

// findAliasedFieldsInStruct finds all fields with alias tags in a struct.
func findAliasedFieldsInStruct(fset *token.FileSet, st *ast.StructType) []AliasedField {
	var fields []AliasedField

	for _, field := range st.Fields.List {
		if field.Tag == nil {
			continue
		}

		// Parse the struct tag
		tagValue := strings.Trim(field.Tag.Value, "`")
		tag := reflect.StructTag(tagValue)

		// Check for alias tag
		aliasTag := tag.Get(AliasTagName)
		if aliasTag == "" {
			continue
		}

		// Parse json tag
		jsonTag := tag.Get("json")
		if jsonTag == "" || jsonTag == "-" {
			log.Printf("WARNING: field has %s tag but no json tag, skipping", AliasTagName)
			continue
		}
		jsonName, omitempty := parseJSONTag(jsonTag)

		// Get field name (skip anonymous/embedded fields for now)
		if len(field.Names) == 0 {
			log.Printf("WARNING: embedded field has %s tag, skipping (not supported)", AliasTagName)
			continue
		}
		fieldName := field.Names[0].Name

		// Get field type as string
		var typeBuf bytes.Buffer
		if err := format.Node(&typeBuf, fset, field.Type); err != nil {
			log.Printf("WARNING: could not format type for field %s: %v", fieldName, err)
			continue
		}

		fields = append(fields, AliasedField{
			Name:      fieldName,
			JSONName:  jsonName,
			AliasName: aliasTag,
			Type:      typeBuf.String(),
			Omitempty: omitempty,
		})
	}

	return fields
}

// parseJSONTag parses a json struct tag into its name and omitempty flag.
func parseJSONTag(tag string) (name string, omitempty bool) {
	parts := strings.Split(tag, ",")
	name = parts[0]
	for _, p := range parts[1:] {
		if p == "omitempty" {
			omitempty = true
		}
	}
	return
}

// findExistingMarshalers finds all types in the package that already have MarshalJSON methods.
func findExistingMarshalers(fset *token.FileSet, pkgPath string) (map[string]bool, error) {
	pkgs, err := parser.ParseDir(fset, pkgPath, sourceFileFilter, 0)
	if err != nil {
		return nil, fmt.Errorf("parsing package: %w", err)
	}

	existing := make(map[string]bool)

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				funcDecl, ok := decl.(*ast.FuncDecl)
				if !ok {
					continue
				}

				// Check if it's a MarshalJSON method
				if funcDecl.Name.Name != "MarshalJSON" {
					continue
				}

				// Check if it has a receiver
				if funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
					continue
				}

				// Extract receiver type name
				recvType := funcDecl.Recv.List[0].Type
				typeName := extractTypeName(recvType)
				if typeName != "" {
					existing[typeName] = true
				}
			}
		}
	}

	return existing, nil
}

// extractTypeName extracts the type name from a receiver expression.
// Handles both value receivers (T) and pointer receivers (*T).
func extractTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			return ident.Name
		}
	}
	return ""
}

// generateMarshalers generates the MarshalJSON implementations for all aliased structs.
func generateMarshalers(pkgName string, structs []AliasedStruct) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, generatedHeader, pkgName)

	for _, s := range structs {
		if err := generateMarshaler(&buf, s); err != nil {
			return nil, fmt.Errorf("generating marshaler for %s: %w", s.Name, err)
		}
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w", err)
	}

	// Fix imports
	result, err := imports.Process("", formatted, nil)
	if err != nil {
		return nil, fmt.Errorf("processing imports: %w", err)
	}

	return result, nil
}

// generateMarshaler generates a MarshalJSON implementation for a single struct.
func generateMarshaler(buf *bytes.Buffer, s AliasedStruct) error {
	// Build the alias field declarations
	var aliasFieldDecls []string
	var aliasFieldAssignments []string

	for _, f := range s.Fields {
		// Build json tag for alias field
		jsonTag := f.AliasName
		if f.Omitempty {
			jsonTag += ",omitempty"
		}

		// Use a unique name for the alias field to avoid conflicts
		aliasFieldName := f.Name + "_alias"

		aliasFieldDecls = append(aliasFieldDecls,
			fmt.Sprintf("\t\t%s %s `json:\"%s\"`", aliasFieldName, f.Type, jsonTag))

		aliasFieldAssignments = append(aliasFieldAssignments,
			fmt.Sprintf("\t\t%s: o.%s,", aliasFieldName, f.Name))
	}

	// Write the method
	fmt.Fprintf(buf, `
  // MarshalJSON implements json.Marshaler to add API alias fields.
  // Generated by aliasgen - DO NOT EDIT.
  func (o %s) MarshalJSON() ([]byte, error) {
        type Original %s
        return json.Marshal(&struct {
                Original
  %s
        }{
                Original: Original(o),
  %s
        })
  }
  `, s.Name, s.Name, strings.Join(aliasFieldDecls, "\n"), strings.Join(aliasFieldAssignments, "\n"))

	return nil
}
